# Generated by Django 4.1.5 on 2023-02-15 02:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(11)])),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='BudgetReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Monthly_Savings', models.IntegerField()),
                ('Total_Monthly_Expenses', models.IntegerField()),
                ('Under_Over_Budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cars', models.IntegerField()),
                ('rent_bill', models.IntegerField()),
                ('mortgage_bill', models.IntegerField()),
                ('mortgage_interest_rate', models.IntegerField()),
                ('gorcerys', models.IntegerField()),
                ('dinning_out', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('internet', models.IntegerField()),
                ('phone_bill', models.IntegerField()),
                ('utilites', models.IntegerField()),
                ('miscellaneous', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('savings_amount', models.IntegerField()),
                ('savings_interest_rate', models.IntegerField()),
                ('amount_in_stocks', models.IntegerField()),
                ('yes_no_401K', models.CharField(max_length=3)),
                ('interest_401K_match', models.IntegerField()),
                ('roth_investing', models.IntegerField()),
                ('roth_amount', models.IntegerField()),
                ('pass_miscellaneous', models.IntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.basemodel')),
                ('email', models.EmailField(max_length=254)),
                ('password_confirmation', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(11)])),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            bases=('users.basemodel',),
        ),
    ]
