# Generated by Django 4.1.5 on 2023-02-01 02:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(11)])),
                ('password', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationForm',
            fields=[
                ('basemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.basemodel')),
                ('email', models.EmailField(max_length=254)),
                ('password_confirmation', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(11)])),
            ],
            bases=('users.basemodel',),
        ),
    ]
