# Generated by Django 4.1.5 on 2023-02-16 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='amount_in_savings',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='pass_miscellaneous',
        ),
        migrations.RemoveField(
            model_name='assets',
            name='roth_amount',
        ),
        migrations.RemoveField(
            model_name='monthlyexpensemodel',
            name='car_payment ',
        ),
        migrations.RemoveField(
            model_name='monthlyexpensemodel',
            name='mortgage_bill',
        ),
        migrations.AddField(
            model_name='assets',
            name='total_Assets',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyexpensemodel',
            name='car_payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyexpensemodel',
            name='total_expenses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assets',
            name='Amount_In_Savings',
            field=models.IntegerField(default=0),
        ),
    ]
