# Generated by Django 4.1.5 on 2023-02-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_registrationform_registrationmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.IntegerField()),
                ('savings_amount', models.IntegerField()),
                ('savings_interest_rate', models.IntegerField()),
                ('amount_in_stocks', models.IntegerField()),
                ('yes_no_401K', models.CharField(max_length=3)),
                ('interest_401K_match', models.IntegerField()),
                ('roth_investing', models.IntegerField()),
                ('roth_amount', models.IntegerField()),
                ('pass_miscellaneous', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BudgetReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Total_Monthly_Savings', models.IntegerField()),
                ('Total_Monthly_Expenses', models.IntegerField()),
                ('Under_Over_Budget', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_cars', models.IntegerField()),
                ('rent_bill', models.IntegerField()),
                ('mortgage_bill', models.IntegerField()),
                ('mortgage_interest_rate', models.IntegerField()),
                ('gorcerys', models.IntegerField()),
                ('dinning_out', models.IntegerField()),
                ('gas', models.IntegerField()),
                ('internet', models.IntegerField()),
                ('phone_bill', models.IntegerField()),
                ('utilites', models.IntegerField()),
                ('miscellaneous', models.IntegerField()),
            ],
        ),
    ]
