# Generated by Django 4.1.5 on 2023-02-14 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_registrationform_registrationmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assets',
            name='user',
        ),
        migrations.RemoveField(
            model_name='budgetreview',
            name='user',
        ),
        migrations.RemoveField(
            model_name='monthlyexpensemodel',
            name='user',
        ),
    ]
