# Generated by Django 4.1.5 on 2023-02-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_savings_amount_assets_amount_in_savings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assets',
            name='Amount_In_Savings',
            field=models.IntegerField(default=0),
        ),
    ]
